///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String pngImagePlaceholder = 'assets/png/imagePlaceholder.png';
  static const String pngImageUserPlaceholder =
      'assets/png/imageUserPlaceholder.png';
  static const String pngLogo = 'assets/png/logo.png';
  static const String pngSplash = 'assets/png/splash.png';
}
